#!/usr/bin/env node
/**
 * Builds the rewards portal project into dist/portal.
 *
 * The portal is the same code as the Slack app, pushed to a SECOND Apps Script
 * project with a different web-app manifest:
 *
 *   Slack project   access ANYONE_ANONYMOUS  — Slack's servers are anonymous
 *   Portal project  access DOMAIN            — staff sign in with actaba.com,
 *                                              so Session.getActiveUser() works
 *
 * One project cannot serve both, because a web app's access setting comes from
 * the manifest of the version it runs. Both projects open the same spreadsheet.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const src = path.join(root, 'src');
const out = path.join(root, 'dist', 'portal');

fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });

fs.readdirSync(src).forEach((f) => {
  if (f === 'appsscript.json') return;
  fs.copyFileSync(path.join(src, f), path.join(out, f));
});

const manifest = JSON.parse(fs.readFileSync(path.join(src, 'appsscript.json'), 'utf8'));
manifest.webapp = { executeAs: 'USER_DEPLOYING', access: 'DOMAIN' };
fs.writeFileSync(path.join(out, 'appsscript.json'), JSON.stringify(manifest, null, 2) + '\n');

// portal/.clasp.json carries the portal's scriptId and the shared spreadsheetId.
const claspSrc = path.join(root, 'portal', '.clasp.json');
let sheetId = process.env.TAILWAG_SPREADSHEET_ID || '';
if (fs.existsSync(claspSrc)) {
  const c = JSON.parse(fs.readFileSync(claspSrc, 'utf8'));
  sheetId = sheetId || c.spreadsheetId || '';
  fs.writeFileSync(path.join(out, '.clasp.json'), JSON.stringify({ scriptId: c.scriptId, rootDir: '.' }, null, 2) + '\n');
}
if (!fs.existsSync(path.join(out, '.clasp.json'))) {
  console.warn('Note: portal/.clasp.json not found — dist/portal has no scriptId, so clasp push will not know where to go.');
}
if (!/^[A-Za-z0-9_-]{20,}$/.test(sheetId)) {
  console.error('No spreadsheet id: set "spreadsheetId" in portal/.clasp.json (or TAILWAG_SPREADSHEET_ID).');
  process.exit(1);
}
fs.writeFileSync(path.join(out, '00a_Portal.gs'),
  '/** Generated by scripts/build-portal.js — the shared Tail Wag spreadsheet. */\n' +
  "var PORTAL_SPREADSHEET_ID = '" + sheetId + "';\n");

console.log('Built ' + fs.readdirSync(out).length + ' files into dist/portal (web app access: DOMAIN).');
